package move;
// Generated 03-feb-2019 13:13:56 by Hibernate Tools 4.3.1



/**
 * Clientes generated by hbm2java
 */
public class Clientes  implements java.io.Serializable {


     private String idCliente;
     private String nombre;
     private String nombreContacto;
     private String cargoContacto;
     private String direccion;
     private String ciudad;
     private String region;
     private String codPostal;
     private String pais;
     private String telefono;
     private String fax;

    public Clientes() {
    }

	
    public Clientes(String idCliente, String nombre) {
        this.idCliente = idCliente;
        this.nombre = nombre;
    }
    public Clientes(String idCliente, String nombre, String nombreContacto, String cargoContacto, String direccion, String ciudad, String region, String codPostal, String pais, String telefono, String fax) {
       this.idCliente = idCliente;
       this.nombre = nombre;
       this.nombreContacto = nombreContacto;
       this.cargoContacto = cargoContacto;
       this.direccion = direccion;
       this.ciudad = ciudad;
       this.region = region;
       this.codPostal = codPostal;
       this.pais = pais;
       this.telefono = telefono;
       this.fax = fax;
    }
   
    public String getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(String idCliente) {
        this.idCliente = idCliente;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getNombreContacto() {
        return this.nombreContacto;
    }
    
    public void setNombreContacto(String nombreContacto) {
        this.nombreContacto = nombreContacto;
    }
    public String getCargoContacto() {
        return this.cargoContacto;
    }
    
    public void setCargoContacto(String cargoContacto) {
        this.cargoContacto = cargoContacto;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }
    public String getRegion() {
        return this.region;
    }
    
    public void setRegion(String region) {
        this.region = region;
    }
    public String getCodPostal() {
        return this.codPostal;
    }
    
    public void setCodPostal(String codPostal) {
        this.codPostal = codPostal;
    }
    public String getPais() {
        return this.pais;
    }
    
    public void setPais(String pais) {
        this.pais = pais;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getFax() {
        return this.fax;
    }
    
    public void setFax(String fax) {
        this.fax = fax;
    }




}


