package move;
// Generated 03-feb-2019 13:13:56 by Hibernate Tools 4.3.1



/**
 * CompaniasDeEnvios generated by hbm2java
 */
public class CompaniasDeEnvios  implements java.io.Serializable {


     private Integer idCompaniaEnvios;
     private String nombreCompania;
     private String telefono;

    public CompaniasDeEnvios() {
    }

	
    public CompaniasDeEnvios(String nombreCompania) {
        this.nombreCompania = nombreCompania;
    }
    public CompaniasDeEnvios(String nombreCompania, String telefono) {
       this.nombreCompania = nombreCompania;
       this.telefono = telefono;
    }
   
    public Integer getIdCompaniaEnvios() {
        return this.idCompaniaEnvios;
    }
    
    public void setIdCompaniaEnvios(Integer idCompaniaEnvios) {
        this.idCompaniaEnvios = idCompaniaEnvios;
    }
    public String getNombreCompania() {
        return this.nombreCompania;
    }
    
    public void setNombreCompania(String nombreCompania) {
        this.nombreCompania = nombreCompania;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }




}


