package move;
// Generated 03-feb-2019 13:13:56 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * EmpleadosSinFoto generated by hbm2java
 */
public class EmpleadosSinFoto  implements java.io.Serializable {


     private Integer id;
     private Integer campo1;
     private String campo2;
     private String campo3;
     private String campo4;
     private String campo5;
     private Date campo6;
     private Date campo7;
     private String campo10;
     private String campo8;
     private String campo9;
     private String campo11;
     private String campo12;
     private String campo13;
     private String campo14;
     private String campo15;
     private String campo16;

    public EmpleadosSinFoto() {
    }

    public EmpleadosSinFoto(Integer campo1, String campo2, String campo3, String campo4, String campo5, Date campo6, Date campo7, String campo10, String campo8, String campo9, String campo11, String campo12, String campo13, String campo14, String campo15, String campo16) {
       this.campo1 = campo1;
       this.campo2 = campo2;
       this.campo3 = campo3;
       this.campo4 = campo4;
       this.campo5 = campo5;
       this.campo6 = campo6;
       this.campo7 = campo7;
       this.campo10 = campo10;
       this.campo8 = campo8;
       this.campo9 = campo9;
       this.campo11 = campo11;
       this.campo12 = campo12;
       this.campo13 = campo13;
       this.campo14 = campo14;
       this.campo15 = campo15;
       this.campo16 = campo16;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Integer getCampo1() {
        return this.campo1;
    }
    
    public void setCampo1(Integer campo1) {
        this.campo1 = campo1;
    }
    public String getCampo2() {
        return this.campo2;
    }
    
    public void setCampo2(String campo2) {
        this.campo2 = campo2;
    }
    public String getCampo3() {
        return this.campo3;
    }
    
    public void setCampo3(String campo3) {
        this.campo3 = campo3;
    }
    public String getCampo4() {
        return this.campo4;
    }
    
    public void setCampo4(String campo4) {
        this.campo4 = campo4;
    }
    public String getCampo5() {
        return this.campo5;
    }
    
    public void setCampo5(String campo5) {
        this.campo5 = campo5;
    }
    public Date getCampo6() {
        return this.campo6;
    }
    
    public void setCampo6(Date campo6) {
        this.campo6 = campo6;
    }
    public Date getCampo7() {
        return this.campo7;
    }
    
    public void setCampo7(Date campo7) {
        this.campo7 = campo7;
    }
    public String getCampo10() {
        return this.campo10;
    }
    
    public void setCampo10(String campo10) {
        this.campo10 = campo10;
    }
    public String getCampo8() {
        return this.campo8;
    }
    
    public void setCampo8(String campo8) {
        this.campo8 = campo8;
    }
    public String getCampo9() {
        return this.campo9;
    }
    
    public void setCampo9(String campo9) {
        this.campo9 = campo9;
    }
    public String getCampo11() {
        return this.campo11;
    }
    
    public void setCampo11(String campo11) {
        this.campo11 = campo11;
    }
    public String getCampo12() {
        return this.campo12;
    }
    
    public void setCampo12(String campo12) {
        this.campo12 = campo12;
    }
    public String getCampo13() {
        return this.campo13;
    }
    
    public void setCampo13(String campo13) {
        this.campo13 = campo13;
    }
    public String getCampo14() {
        return this.campo14;
    }
    
    public void setCampo14(String campo14) {
        this.campo14 = campo14;
    }
    public String getCampo15() {
        return this.campo15;
    }
    
    public void setCampo15(String campo15) {
        this.campo15 = campo15;
    }
    public String getCampo16() {
        return this.campo16;
    }
    
    public void setCampo16(String campo16) {
        this.campo16 = campo16;
    }




}


