package move;
// Generated 03-feb-2019 13:13:56 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Empleados generated by hbm2java
 */
public class Empleados  implements java.io.Serializable {


     private Integer idEmpleado;
     private String apellidos;
     private String nombre;
     private String cargo;
     private String tratamiento;
     private Date fechaNacimiento;
     private Date fechaContratacion;
     private String direccion;
     private String ciudad;
     private String region;
     private String codPostal;
     private String pais;
     private String telDomicilio;
     private String extension;
     private byte[] foto;
     private String notas;
     private Integer jefe;

    public Empleados() {
    }

	
    public Empleados(String apellidos, String nombre) {
        this.apellidos = apellidos;
        this.nombre = nombre;
    }
    public Empleados(String apellidos, String nombre, String cargo, String tratamiento, Date fechaNacimiento, Date fechaContratacion, String direccion, String ciudad, String region, String codPostal, String pais, String telDomicilio, String extension, byte[] foto, String notas, Integer jefe) {
       this.apellidos = apellidos;
       this.nombre = nombre;
       this.cargo = cargo;
       this.tratamiento = tratamiento;
       this.fechaNacimiento = fechaNacimiento;
       this.fechaContratacion = fechaContratacion;
       this.direccion = direccion;
       this.ciudad = ciudad;
       this.region = region;
       this.codPostal = codPostal;
       this.pais = pais;
       this.telDomicilio = telDomicilio;
       this.extension = extension;
       this.foto = foto;
       this.notas = notas;
       this.jefe = jefe;
    }
   
    public Integer getIdEmpleado() {
        return this.idEmpleado;
    }
    
    public void setIdEmpleado(Integer idEmpleado) {
        this.idEmpleado = idEmpleado;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getCargo() {
        return this.cargo;
    }
    
    public void setCargo(String cargo) {
        this.cargo = cargo;
    }
    public String getTratamiento() {
        return this.tratamiento;
    }
    
    public void setTratamiento(String tratamiento) {
        this.tratamiento = tratamiento;
    }
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }
    public Date getFechaContratacion() {
        return this.fechaContratacion;
    }
    
    public void setFechaContratacion(Date fechaContratacion) {
        this.fechaContratacion = fechaContratacion;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }
    public String getRegion() {
        return this.region;
    }
    
    public void setRegion(String region) {
        this.region = region;
    }
    public String getCodPostal() {
        return this.codPostal;
    }
    
    public void setCodPostal(String codPostal) {
        this.codPostal = codPostal;
    }
    public String getPais() {
        return this.pais;
    }
    
    public void setPais(String pais) {
        this.pais = pais;
    }
    public String getTelDomicilio() {
        return this.telDomicilio;
    }
    
    public void setTelDomicilio(String telDomicilio) {
        this.telDomicilio = telDomicilio;
    }
    public String getExtension() {
        return this.extension;
    }
    
    public void setExtension(String extension) {
        this.extension = extension;
    }
    public byte[] getFoto() {
        return this.foto;
    }
    
    public void setFoto(byte[] foto) {
        this.foto = foto;
    }
    public String getNotas() {
        return this.notas;
    }
    
    public void setNotas(String notas) {
        this.notas = notas;
    }
    public Integer getJefe() {
        return this.jefe;
    }
    
    public void setJefe(Integer jefe) {
        this.jefe = jefe;
    }




}


