package move;
// Generated 03-feb-2019 13:13:56 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Pedidos generated by hbm2java
 */
public class Pedidos  implements java.io.Serializable {


     private Integer idPedido;
     private String idCliente;
     private Integer idEmpleado;
     private Date fechaPedido;
     private Date fechaEntrega;
     private Date fechaEnvio;
     private Integer formaEnvio;
     private BigDecimal cargo;
     private String destinatario;
     private String direccionDestinatario;
     private String ciudadDestinatario;
     private String regionDestinatario;
     private String codPostalDestinatario;
     private String paisDestinatario;

    public Pedidos() {
    }

	
    public Pedidos(String idCliente) {
        this.idCliente = idCliente;
    }
    public Pedidos(String idCliente, Integer idEmpleado, Date fechaPedido, Date fechaEntrega, Date fechaEnvio, Integer formaEnvio, BigDecimal cargo, String destinatario, String direccionDestinatario, String ciudadDestinatario, String regionDestinatario, String codPostalDestinatario, String paisDestinatario) {
       this.idCliente = idCliente;
       this.idEmpleado = idEmpleado;
       this.fechaPedido = fechaPedido;
       this.fechaEntrega = fechaEntrega;
       this.fechaEnvio = fechaEnvio;
       this.formaEnvio = formaEnvio;
       this.cargo = cargo;
       this.destinatario = destinatario;
       this.direccionDestinatario = direccionDestinatario;
       this.ciudadDestinatario = ciudadDestinatario;
       this.regionDestinatario = regionDestinatario;
       this.codPostalDestinatario = codPostalDestinatario;
       this.paisDestinatario = paisDestinatario;
    }
   
    public Integer getIdPedido() {
        return this.idPedido;
    }
    
    public void setIdPedido(Integer idPedido) {
        this.idPedido = idPedido;
    }
    public String getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(String idCliente) {
        this.idCliente = idCliente;
    }
    public Integer getIdEmpleado() {
        return this.idEmpleado;
    }
    
    public void setIdEmpleado(Integer idEmpleado) {
        this.idEmpleado = idEmpleado;
    }
    public Date getFechaPedido() {
        return this.fechaPedido;
    }
    
    public void setFechaPedido(Date fechaPedido) {
        this.fechaPedido = fechaPedido;
    }
    public Date getFechaEntrega() {
        return this.fechaEntrega;
    }
    
    public void setFechaEntrega(Date fechaEntrega) {
        this.fechaEntrega = fechaEntrega;
    }
    public Date getFechaEnvio() {
        return this.fechaEnvio;
    }
    
    public void setFechaEnvio(Date fechaEnvio) {
        this.fechaEnvio = fechaEnvio;
    }
    public Integer getFormaEnvio() {
        return this.formaEnvio;
    }
    
    public void setFormaEnvio(Integer formaEnvio) {
        this.formaEnvio = formaEnvio;
    }
    public BigDecimal getCargo() {
        return this.cargo;
    }
    
    public void setCargo(BigDecimal cargo) {
        this.cargo = cargo;
    }
    public String getDestinatario() {
        return this.destinatario;
    }
    
    public void setDestinatario(String destinatario) {
        this.destinatario = destinatario;
    }
    public String getDireccionDestinatario() {
        return this.direccionDestinatario;
    }
    
    public void setDireccionDestinatario(String direccionDestinatario) {
        this.direccionDestinatario = direccionDestinatario;
    }
    public String getCiudadDestinatario() {
        return this.ciudadDestinatario;
    }
    
    public void setCiudadDestinatario(String ciudadDestinatario) {
        this.ciudadDestinatario = ciudadDestinatario;
    }
    public String getRegionDestinatario() {
        return this.regionDestinatario;
    }
    
    public void setRegionDestinatario(String regionDestinatario) {
        this.regionDestinatario = regionDestinatario;
    }
    public String getCodPostalDestinatario() {
        return this.codPostalDestinatario;
    }
    
    public void setCodPostalDestinatario(String codPostalDestinatario) {
        this.codPostalDestinatario = codPostalDestinatario;
    }
    public String getPaisDestinatario() {
        return this.paisDestinatario;
    }
    
    public void setPaisDestinatario(String paisDestinatario) {
        this.paisDestinatario = paisDestinatario;
    }




}


